apiVersion: v1
kind: Service

metadata:
    name: mysql-service
spec:
    type: ClusterIP
    selector:
        database: mysql
    ports:
        - port: 3306
          targetPort: 3306
          protocol: TCP
          name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
    name: mysql-pvc
    labels:
        database: mysql
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: mysql-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            database: mysql
    template:
        metadata:
            labels:
                database: mysql
        spec:
            volumes:
                - name: mysql-storage
                  persistentVolumeClaim:
                      claimName: mysql-pvc
            containers: 
                - name: image-mysql
                  image: image-mysql
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                    - name: mysql-storage
                      mountPath: /var/lib/mysql
                  livenessProbe:
                      exec:
                          command:
                              - sh
                              - /test.sh
                      initialDelaySeconds: 5
                      periodSeconds: 15
