apiVersion: v1
kind: Service

metadata:
    name: influxdb-service
spec:
    type: ClusterIP
    selector:
        database: influxdb
    ports:
        - port: 8086
          targetPort: 8086
          protocol: TCP
          name: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
    name: influxdb-pvc
    labels:
        database: influxdb
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: influxdb-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            database: influxdb
    template:
        metadata:
            labels:
                database: influxdb
        spec:
            volumes:
                - name: influxdb-storage
                  persistentVolumeClaim:
                      claimName: influxdb-pvc
            containers:
                - name: image-influxdb
                  image: image-influxdb
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8086
                  volumeMounts:
                      - name: influxdb-storage
                        mountPath: /var/lib/influxdb
                        subPath: data
                  livenessProbe:
                      exec:
                          command:
                              - sh
                              - /test.sh
                      initialDelaySeconds: 60
                      periodSeconds: 5

