apiVersion: v1
kind: Service

metadata:
    name: influxdb-service
spec:
    type: ClusterIP
    selector:
        database: influxdb
    ports:
        - port: 8086
          targetPort: 8086
          protocol: TCP
          name: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
    name: influxdb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: influxdb-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            database: influxdb
    template:
        metadata:
            labels:
                database: influxdb
        spec:
            volumes:
                - name: database-storage
                  persistentVolumeClaim:
                      claimName: database-pvc
            containers:
                - name: image-influxdb
                  image: image-influxdb
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8086

