apiVersion: v1
kind: Service

metadata:
    name: mysql-service
spec:
    type: ClusterIP
    selector:
        database: mysql
    ports:
        - port: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
    name: mysql-pvc
    labels:
        database: mysql
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: mysql-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            database: mysql
    template:
        metadata:
            labels:
                database: mysql
        spec:
            containers:
                - name: image-mysql
                  image: image-mysql
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3306
