apiVersion: v1
kind: Service

metadata:
    name: nginx-service
spec:
    type: LoadBalancer
    selector:
        app: nginx
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          name: http
        - port: 443
          targetPort: 443
          protocol: TCP
          name: https
---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: nginx-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: image-nginx
                  image: image-nginx
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 80
                      - containerPort: 443
